### ISSUE TITLE
Viewing Debugbar

### ISSUE THREAD

**Issue by jesseschutt** [acidjazz/laranuxt#1]
Hi! 

I'm curious if you are able to view the debugbar within your Nuxt application in this setup?

Thanks!

**Comment by acidjazz** [comment]
@jesseschutt on my dev environment it was never an issue, but it has been an ongoing issue on staging though, i've recently finally found a fix for this and will update this repo accordingly.

**Comment by acidjazz** [comment]
@jesseschutt I've updated the config, env, and readme to have this work right out of the box, you should instantly be able to see the debugbar at `/api/example`
