### ISSUE TITLE
css does not load if using production build

### ISSUE THREAD

**Issue by Venipa** [acidjazz/laranuxt#17]
![image](https://user-images.githubusercontent.com/17952364/93030622-a2466780-f624-11ea-88fb-749d0a027a1b.png)
app.css just returns error css from nuxt.

**Comment by acidjazz** [comment]
thanks for reporting this!

**Comment by SerjoA** [comment]
still the same for me, i just cloned it

**Comment by SerjoA** [comment]
nvm it was changer repository with old version
